<a href="https://colab.research.google.com/github/MagdaSousa/Estudo_Pandas/blob/master/missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as  pd
import numpy as np

In [3]:
datas = pd.date_range('20200101',periods=60,freq='D')
df = pd.DataFrame(np.random.randn(60,5),index = datas, columns=list('ABCDE'))

In [4]:
df.head(3)

                   A         B         C         D         E
2020-01-01 -1.312639 -1.128776  1.702460 -1.707550  0.945416
2020-01-02  0.328773  0.412511 -1.185524  1.267114 -0.627723
2020-01-03 -0.989285  0.318839 -0.596666  1.722434  0.780990

In [5]:
df['F'] = df.A[df.A > 0]

In [6]:
df.head(3)

                   A         B         C         D         E         F
2020-01-01 -1.312639 -1.128776  1.702460 -1.707550  0.945416       NaN
2020-01-02  0.328773  0.412511 -1.185524  1.267114 -0.627723  0.328773
2020-01-03 -0.989285  0.318839 -0.596666  1.722434  0.780990       NaN

In [7]:
df2 =df.copy()
df3 =df.copy()

In [8]:
df2.dropna()# deletando valores NaN, ou seja remove a linha inteira que cont√©m um valor NaN

                   A         B         C         D         E         F
2020-01-02  0.328773  0.412511 -1.185524  1.267114 -0.627723  0.328773
2020-01-05  1.272328  0.490564 -1.380377  1.310594  0.178733  1.272328
2020-01-06  0.192811  1.267995 -0.583468  0.672847  1.132811  0.192811
2020-01-07  0.798894  0.114351 -0.101547  1.065852  0.679494  0.798894
2020-01-08  1.797045  0.319900 -1.253097  0.334197  0.345171  1.797045
2020-01-09  0.230566  0.788388  0.125745 -0.044401 -0.672889  0.230566
2020-01-12  2.369207  0.622210 -0.863388 -0.170187  1.574415  2.369207
2020-01-13  0.278265 -0.140531 -0.031537 -0.468068 -0.833158  0.278265
2020-01-17  1.285513  0.396449 -1.105870 -0.439851 -0.027109  1.285513
2020-01-22  2.274644  0.734529 -0.019530 -1.701957 -0.648430  2.274644
2020-01-23  0.053600  0.028319 -0.111342  0.380789  0.491104  0.053600
2020-01-24  1.380892 -0.729917 -0.149701 -1.320046  0.427489  1.380892
2020-01-25  0.627722 -2.302767 -1.350911  0.687480 -0.221829  0.627722
2020-01-26  0.132717 -2.725037 -0.380766 -0.583834  0.535071  0.132717
2020-01-29  1.181484 -0.763413 -0.516002  0.399646  0.261645  1.181484
2020-01-30  1.580981  0.531109 -1.156165 -0.602050 -0.604518  1.580981
2020-02-01  0.925051  0.581677 -0.587948 -1.385152  0.195880  0.925051
2020-02-02  2.807606 -0.148223 -0.126341  0.070012 -0.019199  2.807606
2020-02-04  0.929532  0.484276 -0.105048  0.063464  0.683866  0.929532
2020-02-07  1.809393  0.357462 -0.451363  1.583351  1.312583  1.809393
2020-02-09  1.396107 -1.280082  0.992820  1.243644  0.229024  1.396107
2020-02-10  0.926368 -0.716192 -0.335543  0.409684  0.694707  0.926368
2020-02-15  0.194993 -0.912745  0.571451 -0.087817 -0.341408  0.194993
2020-02-16  0.307051  0.442535  1.124028 -2.006457  0.461453  0.307051
2020-02-18  0.202555 -0.555248  1.081779  0.797213  1.281389  0.202555
2020-02-19  1.433334 -1.523244  0.236608  0.257678 -0.569954  1.433334
2020-02-20  0.659584  1.268659  0.590879  0.297800 -0.051738  0.659584
2020-02-22  0.985639 -0.900968  0.562876 -0.064497 -2.022074  0.985639
2020-02-24  1.519470  0.400042  1.071519 -0.190787 -0.225850  1.519470
2020-02-27  1.502360 -0.238194  0.114587  1.158682  0.298472  1.502360
2020-02-29  0.300462  0.121993 -0.344070  1.264108 -0.123646  0.300462

In [9]:
df.shape

(60, 6)

In [11]:
df2.dropna().shape

(31, 6)

In [12]:
df3.head(3)

                   A         B         C         D         E         F
2020-01-01 -1.312639 -1.128776  1.702460 -1.707550  0.945416       NaN
2020-01-02  0.328773  0.412511 -1.185524  1.267114 -0.627723  0.328773
2020-01-03 -0.989285  0.318839 -0.596666  1.722434  0.780990       NaN

In [14]:
df3.fillna(np.mean(df3.A)).head(3)#Substituir os valores NaN, pela m√©dia de valores da coluna A.Neste caso sem
# espec√≠ficar a coluna ele ir√° substituir em qualquer lugar que n√£o houver registro

                   A         B         C         D         E         F
2020-01-01 -1.312639 -1.128776  1.702460 -1.707550  0.945416  0.154370
2020-01-02  0.328773  0.412511 -1.185524  1.267114 -0.627723  0.328773
2020-01-03 -0.989285  0.318839 -0.596666  1.722434  0.780990  0.154370

In [15]:
df3.F.fillna(np.mean(df3.A)).head(3)# Colocando o F, digo que o valor a ser inserido deve ser apenas na coluna F

2020-01-01    0.154370
2020-01-02    0.328773
2020-01-03    0.154370
Freq: D, Name: F, dtype: float64

In [17]:
df4 =df.copy()
df4.fillna(value=8888)

                   A         B         C         D         E            F
2020-01-01 -1.312639 -1.128776  1.702460 -1.707550  0.945416  8888.000000
2020-01-02  0.328773  0.412511 -1.185524  1.267114 -0.627723     0.328773
2020-01-03 -0.989285  0.318839 -0.596666  1.722434  0.780990  8888.000000
2020-01-04 -1.629667  2.292979  0.011301  1.723246 -1.597314  8888.000000
2020-01-05  1.272328  0.490564 -1.380377  1.310594  0.178733     1.272328
2020-01-06  0.192811  1.267995 -0.583468  0.672847  1.132811     0.192811
2020-01-07  0.798894  0.114351 -0.101547  1.065852  0.679494     0.798894
2020-01-08  1.797045  0.319900 -1.253097  0.334197  0.345171     1.797045
2020-01-09  0.230566  0.788388  0.125745 -0.044401 -0.672889     0.230566
2020-01-10 -1.417207 -0.552413  0.213787 -1.324413 -0.989501  8888.000000
2020-01-11 -0.912963  0.511876  0.458718 -0.353324  0.118006  8888.000000
2020-01-12  2.369207  0.622210 -0.863388 -0.170187  1.574415     2.369207
2020-01-13  0.278265 -0.140531 -0.031537 -0.468068 -0.833158     0.278265
2020-01-14 -0.221724  0.206862  1.975590 -0.124762  0.507875  8888.000000
2020-01-15 -0.577047 -0.294117  2.199552  0.397498  1.125348  8888.000000
2020-01-16 -0.699277  1.188347 -0.011723  0.663867 -0.169004  8888.000000
2020-01-17  1.285513  0.396449 -1.105870 -0.439851 -0.027109     1.285513
2020-01-18 -1.146667 -0.368841  1.872185  1.015412  0.539852  8888.000000
2020-01-19 -1.865238  1.617837  1.224305  0.309678 -0.854332  8888.000000
2020-01-20 -0.794247  0.966459  0.887986  0.009201 -3.594047  8888.000000
2020-01-21 -0.504431  0.714945  0.023393 -0.345512 -0.052740  8888.000000
2020-01-22  2.274644  0.734529 -0.019530 -1.701957 -0.648430     2.274644
2020-01-23  0.053600  0.028319 -0.111342  0.380789  0.491104     0.053600
2020-01-24  1.380892 -0.729917 -0.149701 -1.320046  0.427489     1.380892
2020-01-25  0.627722 -2.302767 -1.350911  0.687480 -0.221829     0.627722
2020-01-26  0.132717 -2.725037 -0.380766 -0.583834  0.535071     0.132717
2020-01-27 -1.836109  0.743299 -0.478547 -0.294269  0.618145  8888.000000
2020-01-28 -0.747094  1.897308 -1.369530 -0.021240 -0.308028  8888.000000
2020-01-29  1.181484 -0.763413 -0.516002  0.399646  0.261645     1.181484
2020-01-30  1.580981  0.531109 -1.156165 -0.602050 -0.604518     1.580981
2020-01-31 -0.363218  0.639878 -0.616922  1.137647  0.569348  8888.000000
2020-02-01  0.925051  0.581677 -0.587948 -1.385152  0.195880     0.925051
2020-02-02  2.807606 -0.148223 -0.126341  0.070012 -0.019199     2.807606
2020-02-03 -0.139177 -0.349418  0.103008  0.980329  1.057015  8888.000000
2020-02-04  0.929532  0.484276 -0.105048  0.063464  0.683866     0.929532
2020-02-05 -1.621433  0.197230  1.091701 -0.065489 -0.717453  8888.000000
2020-02-06 -0.095815 -1.681540  1.503792 -1.201689  0.401911  8888.000000
2020-02-07  1.809393  0.357462 -0.451363  1.583351  1.312583     1.809393
2020-02-08 -0.617259 -1.841617  0.629737 -0.225075 -0.981821  8888.000000
2020-02-09  1.396107 -1.280082  0.992820  1.243644  0.229024     1.396107
2020-02-10  0.926368 -0.716192 -0.335543  0.409684  0.694707     0.926368
2020-02-11 -0.166142  2.564697 -0.702188  0.956649 -0.953945  8888.000000
2020-02-12 -0.630823 -0.333989 -2.576442 -0.495654  0.090368  8888.000000
2020-02-13 -0.631092  0.327866 -2.008542 -0.735580  0.116038  8888.000000
2020-02-14 -1.103160  0.881101 -1.574318 -0.364437 -1.015767  8888.000000
2020-02-15  0.194993 -0.912745  0.571451 -0.087817 -0.341408     0.194993
2020-02-16  0.307051  0.442535  1.124028 -2.006457  0.461453     0.307051
2020-02-17 -0.724002 -0.077630 -0.007374 -0.219189  0.572709  8888.000000
2020-02-18  0.202555 -0.555248  1.081779  0.797213  1.281389     0.202555
2020-02-19  1.433334 -1.523244  0.236608  0.257678 -0.569954     1.433334
2020-02-20  0.659584  1.268659  0.590879  0.297800 -0.051738     0.659584
2020-02-21 -0.395288  0.637431 -0.325641 -1.114188 -0.001368  8888.000000
2020-02-22  0.985639 -0.900968  0.562876 -0.064497 -2.022074     0.985639
2020-02-23 -0.911727 -0.315117  1.404512  0.193309 -2.154278  8888.000000
2020-02-24  1.519470  0.400042  1.071519 -0.190787 -0.225850     1.519470
2020-02-25 -0.163822 -1.226781 -0.831578  0.743762  0.070372  8888.000000
2020-02-26 -0.166553  0.979136  0.448116  0.203083  0.929974  8888.000000
2020-02-27  1.502360 -0.238194  0.114587  1.158682  0.298472     1.502360
2020-02-28 -0.039674  0.512202 -0.523531  0.485505  0.485195  8888.000000
2020-02-29  0.300462  0.121993 -0.344070  1.264108 -0.123646     0.300462